### ISSUE TITLE
Don't work for resized window

### ISSUE THREAD

**Issue by bobwong89757** [marijnz/unity-toolbar-extender#3] opened 2018-11-06 06:59 UTC
Don't work for resized window, can triggered by resize unity window
![image](https://user-images.githubusercontent.com/6356061/48047851-63e3f400-e1d4-11e8-9da3-f2749b48bbb8.png)
![image](https://user-images.githubusercontent.com/6356061/48047870-6fcfb600-e1d4-11e8-8be6-2f79cd29a433.png)

**Comment by marijnz** [comment] 2018-11-06 08:18
Hi, thanks for opening. This is on Mac right? You could still checkout and try https://github.com/marijnz/unity-toolbar-extender/tree/potential_windows_fix? Resizing the Unity application window should work fine, I just tried it again to make sure, and it works for me. Do you have reproduction steps?

**Comment by bobwong89757** [comment] 2018-11-07 01:22
Hi,marijnz,thank you for the feedback so quickly,I have checkout the new branch but it was not works for me and I works on Mac too.
![2018-11-07 09 22 03](https://user-images.githubusercontent.com/6356061/48104476-a1955b00-e26e-11e8-9a4a-e3d836589c7f.gif)

**Comment by marijnz** [comment] 2018-11-07 12:17
Hey. So by not working, you mean it's not updating **while** you're resizing right? After it, it snaps to the right position and works as usual? So in other words, it's just the visual glitch?

**Comment by bobwong89757** [comment] 2018-11-08 01:04
![image](https://user-images.githubusercontent.com/6356061/48171065-36628c00-e335-11e8-879c-cf88849ba3b5.png)
Yes,it's a visual glitch like these.

**Comment by marijnz** [comment] 2018-11-12 17:43
Fixed in https://github.com/marijnz/unity-toolbar-extender/pull/7 which got merged to master. You can double check and close the issue if all is good.

**Closed as completed** 2018-11-13 11:20 UTC
